name: Rollback 5G Routes

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Test Workflow
        run: echo "Workflow working successfully"